from datetime import datetime


def generate_report(report):
    """
    Generate a formatted inspection report.
    Returns a string.
    """

    report_lines = []

    report_lines.append("=" * 60)
    report_lines.append("SAFESIGHT AI INSPECTION REPORT")
    report_lines.append("=" * 60)

    report_lines.append(f"Image: {report.get('image', 'Unknown')}")
    report_lines.append(f"Site: {report.get('site_name', 'Unknown')}")
    report_lines.append(f"Date: {report.get('date', datetime.now())}")

    report_lines.append("")

    report_lines.append("WORKER STATISTICS")
    report_lines.append("-" * 40)
    report_lines.append(f"Total Workers : {report.get('total_workers', 0)}")
    report_lines.append(f"Safe Workers  : {report.get('safe_workers', 0)}")
    report_lines.append(f"Unsafe Workers: {report.get('unsafe_workers', 0)}")
    report_lines.append(
        f"Compliance    : {report.get('compliance_rate', 0)}%"
    )

    report_lines.append("")
    report_lines.append(f"Status: {report.get('status', 'Unknown')}")

    report_lines.append("")
    report_lines.append(f"Risk Level: {report.get('risk_level', 'Unknown')}")

    report_lines.append("")

    missing = report.get("missing", [])

    if missing:
        report_lines.append("Missing PPE")
        report_lines.append("-" * 40)

        for item in missing:
            report_lines.append(f"• {item}")
    else:
        report_lines.append("No PPE violations detected.")

    report_lines.append("")

    recommendations = report.get("recommendations", [])

    if recommendations:
        report_lines.append("Recommendations")
        report_lines.append("-" * 40)

        for rec in recommendations:
            report_lines.append(f"• {rec}")

    workers = report.get("workers", [])

    if workers:
        report_lines.append("")
        report_lines.append("Worker Details")
        report_lines.append("-" * 40)

        for worker in workers:

            report_lines.append(
                f"Worker {worker.get('worker_id', 'Unknown')}"
            )

            report_lines.append(
                f"Status : {worker.get('status', 'Unknown')}"
            )

            missing_items = worker.get("missing", [])

            if missing_items:
                report_lines.append(
                    f"Missing PPE : {', '.join(missing_items)}"
                )
            else:
                report_lines.append("Missing PPE : None")

            report_lines.append("")

    report_lines.append("=" * 60)
    report_lines.append("Generated by SAFESIGHT AI")
    report_lines.append("=" * 60)

    return "\n".join(report_lines)